### ISSUE TITLE
[Feat] 마이페이지뷰

### ISSUE THREAD

**Issue by sooohi** [Team-TrackUs/Trackus-iOS#25]
## Feature
마이페이지뷰

## Todo
- [x] 캘린더 ui 수정
- [x] 이미지 캐싱
- [x] 세그먼트 ui 수정
- [x] 로그아웃 기능 구현
- [x] 회원탈퇴 기능 구현
- [x] 다른사용자 계정 ui
- [x] 차단된 계정 관리 
- [x] 차단 해제 및 이미지 변경
- [x] 신고하기 버튼 클릭시 내용 저장
- [x] 사용자 데이터 받아오기(기록과 글)
- [x] 탭바 사라짐 현상
- [x] 배경 터치시 키보드 내림 처리
- [x] 회원탈퇴 버튼 고정 및 디자인
- [x] 프로필 이미지 고정
