### ISSUE TITLE
[Feat] 마이페이지 부분 수정 사항 작업

### ISSUE THREAD

**Issue by sooohi** [Team-TrackUs/Trackus-iOS#49]
## Feature
정기회의때 나온 수정 사항 작업

## Todo
- [x] 이용약관, 오프소스/라이센스 뷰 추가
- [x] 글 목록 클릭 시 글 디테일뷰로 이동
- [x] 설정, 회원탈퇴 탭바 제거
- [x] 모든 사용자 삭제(차단된 계정만 볼 수 있도록 수정)
- [x] 러닝기록 수정(제목 / 총합 / 오늘의 데이터)
- [x] 프로필변집뷰에서 닉네임 ui 변경 및 중복 제거 및 유효성 검사 기능 추가
- [x] 사용자 신고 시 reportIDList에 추가
