### ISSUE TITLE
[Fix] 리젝 사유 보완

### ISSUE THREAD

**Issue by Choe-ju** [Team-TrackUs/Trackus-iOS#53]
## Fix
- 리젝 사유 관련사항 보완
<img width="1279" alt="image" src="https://github.com/Team-TrackUs/Trackus-iOS/assets/144399406/797592a9-e852-4151-82fb-a6fb1357aa84">

## Todo
- [x] 1.5 문의하기 안내 영상 촬영
- [x] 2.1 위젯 사용 관련 영상 촬영
- [x] 2.3 프로젝트 명칭 수정
- [x] 5.1.1 권한 요청 멘트 상세히 변경
